package fi.joniharju.financeapp.mapper;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.junit.jupiter.api.Test;

import fi.joniharju.financeapp.dto.CategoryResponse;
import fi.joniharju.financeapp.dto.TransactionResponse;
import fi.joniharju.financeapp.entity.AppUser;
import fi.joniharju.financeapp.entity.Category;
import fi.joniharju.financeapp.entity.Transaction;
import fi.joniharju.financeapp.entity.TransactionType;

public class DtoMapperTest {

    // Manually set the Id fields because they are usually autogenerated when
    // inputted to database, but we dont do that here.

    @Test
    void toTransactionResponseWithCategoryMapsAllFields() {
        AppUser testUser = new AppUser("Joni Harju", "test123", "joni@email.com");
        Category testCategory = new Category("Groceries", testUser, null);

        Transaction transaction = new Transaction(new BigDecimal("10.00"), LocalDate.now(),
                "Test description", TransactionType.EXPENSE, testUser, testCategory);
        transaction.setId(1L);

        TransactionResponse response = DtoMapper.toTransactionResponse(transaction);

        assertEquals(transaction.getId(), response.getId());
        assertEquals(transaction.getAmount(), response.getAmount());
        assertEquals(transaction.getDate(), response.getDate());
        assertEquals(transaction.getDescription(), response.getDescription());
        assertEquals(transaction.getType(), response.getType());
        assertEquals(testCategory.getName(), response.getCategoryName());
    }

    @Test
    void toTransactionResponseWithNullCategoryMapsAllFields() {

        AppUser testUser = new AppUser("Joni Harju", "test123", "joni@email.com");
        Transaction transaction = new Transaction(new BigDecimal("10.00"), LocalDate.now(),
                "Test description", TransactionType.EXPENSE, testUser, null);
        transaction.setId(1L);

        TransactionResponse response = DtoMapper.toTransactionResponse(transaction);

        assertEquals(transaction.getId(), response.getId());
        assertEquals(transaction.getAmount(), response.getAmount());
        assertEquals(transaction.getDate(), response.getDate());
        assertEquals(transaction.getDescription(), response.getDescription());
        assertEquals(transaction.getType(), response.getType());
        assertEquals(null, response.getCategoryName());
    }

    @Test
    void toTransactionResponseWithNullDescriptionMapsAllFields() {
        AppUser testUser = new AppUser("Joni Harju", "test123", "joni@email.com");
        Category testCategory = new Category("Groceries", testUser, null);
        Transaction transaction = new Transaction(new BigDecimal("10.00"), LocalDate.now(),
                null, TransactionType.EXPENSE, testUser, testCategory);
        transaction.setId(1L);

        TransactionResponse response = DtoMapper.toTransactionResponse(transaction);

        assertEquals(transaction.getId(), response.getId());
        assertEquals(transaction.getAmount(), response.getAmount());
        assertEquals(transaction.getDate(), response.getDate());
        assertEquals(transaction.getType(), response.getType());
        assertEquals(testCategory.getName(), response.getCategoryName());
        assertEquals(null, response.getDescription());
    }

    @Test
    void toCategoryresponseMapsAllFields() {
        AppUser testUser = new AppUser("Joni Harju", "test123", "joni@email.com");
        Category testCategory = new Category("Groceries", testUser, null);

        testCategory.setId(1L);
        CategoryResponse response = DtoMapper.toCategoryResponse(testCategory);

        assertEquals(testCategory.getName(), response.getName());
        assertEquals(testCategory.getId(), response.getId());

    }

}
